# Generated by Django 4.1.3 on 2022-11-11 11:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliotecasApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='libro',
            old_name='fecha_publicacion',
            new_name='fecha_adquisicion',
        ),
        migrations.RemoveField(
            model_name='libro',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='libro',
            name='genero',
        ),
        migrations.RemoveField(
            model_name='libro',
            name='idioma',
        ),
        migrations.AddField(
            model_name='prestamo',
            name='fecha_devolucion_real',
            field=models.DateField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='socio',
            name='avisos_penalizacion',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)]),
        ),
        migrations.AddField(
            model_name='socio',
            name='bloqueado_hasta',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
