# Generated by Django 4.1.3 on 2022-11-25 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliotecasApp', '0003_socio_fecha_alta_alter_libro_fecha_adquisicion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='codigo',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
