# Generated by Django 4.1.3 on 2022-12-02 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliotecasApp', '0004_alter_libro_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamo',
            name='fecha_devolucion_real',
            field=models.DateField(blank=True, null=True),
        ),
    ]
